Upload Solution Codility Lesson05.GenomicRangeQuery
pro00er/algorithmSolution pull request #17
Opened 2018-07-01 01:12 UTC by HojinJava

## 내용
작성중.

2018-07-01 02:59 UTC, syohnet requested changes
해당 폴더에 맞는 파일만 올려주세요

2018-07-01 02:59 UTC, ohahohah commented on hojin/Algorithm/codility/lesson05/PassingCars.md
> +			if(total >1000000000){
input 유효성 검사 필요없지 않나요?

2018-07-13 00:57 UTC, kimsunoh reviewed
첫번째 방법을 두번째 방법으로 바꿀때, 첫번째 방법의 개선점을 고치기 위한 고민이 보여서 좋았습니다. 
좋은 풀이 감사드립니다.

2018-07-13 00:57 UTC, kimsunoh commented on hojin/Algorithm/codility/lesson05/PassingCars.md
> +## 시간복잡도를 주링기 위해 생각한 점, 반영한 점
'주링기' 오탈자 있습니다

2025-11-26 06:45 UTC, closed without merging